In [2]:
import bamboolib as bam #easy to do data manipulation and highly recommend going to https://bamboolib.8080labs.com/ and that will help you follow along
import pandas as pd #data manipulation
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [285]:
df = pd.read_excel(r'C:\Users\sreed\Downloads\marketing_campaign.xlsx')

In [252]:
df

         ID  Year_Birth   Education Marital_Status   Income  Kidhome  \
0      5524        1957  Graduation         Single  58138.0        0   
1      2174        1954  Graduation         Single  46344.0        1   
2      4141        1965  Graduation       Together  71613.0        0   
3      6182        1984  Graduation       Together  26646.0        1   
4      5324        1981         PhD        Married  58293.0        1   
...     ...         ...         ...            ...      ...      ...   
2235  10870        1967  Graduation        Married  61223.0        0   
2236   4001        1946         PhD       Together  64014.0        2   
2237   7270        1981  Graduation       Divorced  56981.0        0   
2238   8235        1956      Master       Together  69245.0        0   
2239   9405        1954         PhD        Married  52869.0        1   

      Teenhome Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  \
0            0  2012-09-04       58       635  ...            

Master and 2n Cycle are same. Graduation is undergraduate

In [286]:


df.loc[df["Education"] == "Graduation", "Education"] = "Undergraduate"
df.loc[df["Education"] == "2n Cycle", "Education"] = "Master"



In [39]:
df

         ID  Year_Birth      Education Marital_Status   Income  Kidhome  \
0      5524        1957  Undergraduate         Single  58138.0        0   
1      2174        1954  Undergraduate         Single  46344.0        1   
2      4141        1965  Undergraduate       Together  71613.0        0   
3      6182        1984  Undergraduate       Together  26646.0        1   
4      5324        1981            PhD        Married  58293.0        1   
...     ...         ...            ...            ...      ...      ...   
2235  10870        1967  Undergraduate        Married  61223.0        0   
2236   4001        1946            PhD       Together  64014.0        2   
2237   7270        1981  Undergraduate       Divorced  56981.0        0   
2238   8235        1956         Master       Together  69245.0        0   
2239   9405        1954            PhD        Married  52869.0        1   

      Teenhome Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  \
0            0  2012-09-04

Convert YOLO, Absurd and Alone to Single 

In [287]:
df.loc[df["Marital_Status"] == "YOLO", "Marital_Status"] = "Single"
df.loc[df["Marital_Status"] == "Absurd", "Marital_Status"] = "Single"
df.loc[df["Marital_Status"] == "Alone", "Marital_Status"] = "Single"


In [255]:
df

         ID  Year_Birth      Education Marital_Status   Income  Kidhome  \
0      5524        1957  Undergraduate         Single  58138.0        0   
1      2174        1954  Undergraduate         Single  46344.0        1   
2      4141        1965  Undergraduate       Together  71613.0        0   
3      6182        1984  Undergraduate       Together  26646.0        1   
4      5324        1981            PhD        Married  58293.0        1   
...     ...         ...            ...            ...      ...      ...   
2235  10870        1967  Undergraduate        Married  61223.0        0   
2236   4001        1946            PhD       Together  64014.0        2   
2237   7270        1981  Undergraduate       Divorced  56981.0        0   
2238   8235        1956         Master       Together  69245.0        0   
2239   9405        1954            PhD        Married  52869.0        1   

      Teenhome Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  \
0            0  2012-09-04

Replace missing values in income with median 

In [288]:
df[['Income']] = df[['Income']].fillna(df[['Income']].median())


Change datatype of date customer to datetime

In [289]:
df['Dt_Customer']= pd.to_datetime(df['Dt_Customer'])


In [49]:
df

         ID  Year_Birth      Education Marital_Status   Income  Kidhome  \
0      5524        1957  Undergraduate         Single  58138.0        0   
1      2174        1954  Undergraduate         Single  46344.0        1   
2      4141        1965  Undergraduate       Together  71613.0        0   
3      6182        1984  Undergraduate       Together  26646.0        1   
4      5324        1981            PhD        Married  58293.0        1   
...     ...         ...            ...            ...      ...      ...   
2235  10870        1967  Undergraduate        Married  61223.0        0   
2236   4001        1946            PhD       Together  64014.0        2   
2237   7270        1981  Undergraduate       Divorced  56981.0        0   
2238   8235        1956         Master       Together  69245.0        0   
2239   9405        1954            PhD        Married  52869.0        1   

      Teenhome Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  \
0            0  2012-09-04

In [290]:
from datetime import date
today = date. today()
#age = today.year - df['Year_Birth']
df['Age'] = df.apply(lambda row: today.year -
                                  (row.Year_Birth), axis = 1)

In [51]:
df

         ID  Year_Birth      Education Marital_Status   Income  Kidhome  \
0      5524        1957  Undergraduate         Single  58138.0        0   
1      2174        1954  Undergraduate         Single  46344.0        1   
2      4141        1965  Undergraduate       Together  71613.0        0   
3      6182        1984  Undergraduate       Together  26646.0        1   
4      5324        1981            PhD        Married  58293.0        1   
...     ...         ...            ...            ...      ...      ...   
2235  10870        1967  Undergraduate        Married  61223.0        0   
2236   4001        1946            PhD       Together  64014.0        2   
2237   7270        1981  Undergraduate       Divorced  56981.0        0   
2238   8235        1956         Master       Together  69245.0        0   
2239   9405        1954            PhD        Married  52869.0        1   

      Teenhome Dt_Customer  Recency  MntWines  ...  AcceptedCmp3  \
0            0  2012-09-04     

In [52]:
for col in df.columns:
    print(col)

ID
Year_Birth
Education
Marital_Status
Income
Kidhome
Teenhome
Dt_Customer
Recency
MntWines
MntFruits
MntMeatProducts
MntFishProducts
MntSweetProducts
MntGoldProds
NumDealsPurchases
NumWebPurchases
NumCatalogPurchases
NumStorePurchases
NumWebVisitsMonth
AcceptedCmp3
AcceptedCmp4
AcceptedCmp5
AcceptedCmp1
AcceptedCmp2
Complain
Z_CostContact
Z_Revenue
Response
Age


In [291]:
df = df[df['Age'] <= 120]


In [54]:
df

         ID  Year_Birth      Education Marital_Status   Income  Kidhome  \
0      5524        1957  Undergraduate         Single  58138.0        0   
1      2174        1954  Undergraduate         Single  46344.0        1   
2      4141        1965  Undergraduate       Together  71613.0        0   
3      6182        1984  Undergraduate       Together  26646.0        1   
4      5324        1981            PhD        Married  58293.0        1   
...     ...         ...            ...            ...      ...      ...   
2235  10870        1967  Undergraduate        Married  61223.0        0   
2236   4001        1946            PhD       Together  64014.0        2   
2237   7270        1981  Undergraduate       Divorced  56981.0        0   
2238   8235        1956         Master       Together  69245.0        0   
2239   9405        1954            PhD        Married  52869.0        1   

      Teenhome Dt_Customer  Recency  MntWines  ...  AcceptedCmp3  \
0            0  2012-09-04     

In [292]:
df = pd.get_dummies(df, columns=['Education'],  drop_first = True)

df

         ID  Year_Birth Marital_Status   Income  Kidhome  Teenhome  \
0      5524        1957         Single  58138.0        0         0   
1      2174        1954         Single  46344.0        1         1   
2      4141        1965       Together  71613.0        0         0   
3      6182        1984       Together  26646.0        1         0   
4      5324        1981        Married  58293.0        1         0   
...     ...         ...            ...      ...      ...       ...   
2235  10870        1967        Married  61223.0        0         1   
2236   4001        1946       Together  64014.0        2         1   
2237   7270        1981       Divorced  56981.0        0         0   
2238   8235        1956       Together  69245.0        0         1   
2239   9405        1954        Married  52869.0        1         1   

     Dt_Customer  Recency  MntWines  MntFruits  ...  AcceptedCmp1  \
0     2012-09-04       58       635         88  ...             0   
1     2014-03-08     

In [294]:
df = pd.get_dummies(df, columns=['Marital_Status'], drop_first = True)

df

         ID  Year_Birth   Income  Kidhome  Teenhome Dt_Customer  Recency  \
0      5524        1957  58138.0        0         0  2012-09-04       58   
1      2174        1954  46344.0        1         1  2014-03-08       38   
2      4141        1965  71613.0        0         0  2013-08-21       26   
3      6182        1984  26646.0        1         0  2014-02-10       26   
4      5324        1981  58293.0        1         0  2014-01-19       94   
...     ...         ...      ...      ...       ...         ...      ...   
2235  10870        1967  61223.0        0         1  2013-06-13       46   
2236   4001        1946  64014.0        2         1  2014-06-10       56   
2237   7270        1981  56981.0        0         0  2014-01-25       91   
2238   8235        1956  69245.0        0         1  2014-01-24        8   
2239   9405        1954  52869.0        1         1  2012-10-15       40   

      MntWines  MntFruits  MntMeatProducts  ...  Z_Revenue  Response  Age  \
0         

In [295]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
test = df.drop(['Response','AcceptedCmp5','ID','Year_Birth','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5','Complain','Z_Revenue','Dt_Customer'],axis=1)
vif_data["feature"] = test.columns

# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(test.values, i)
                          for i in range(len(test.columns))]
  
print(vif_data)

                    feature         VIF
0                    Income    2.199974
1                   Kidhome    1.875355
2                  Teenhome    1.613900
3                   Recency    1.008551
4                  MntWines    2.848439
5                 MntFruits    1.945879
6           MntMeatProducts    2.881439
7           MntFishProducts    2.104923
8          MntSweetProducts    1.912935
9              MntGoldProds    1.519245
10        NumDealsPurchases    1.658799
11          NumWebPurchases    1.927028
12      NumCatalogPurchases    2.980676
13        NumStorePurchases    2.352714
14        NumWebVisitsMonth    2.282571
15             AcceptedCmp1    1.227431
16            Z_CostContact  104.530575
17                      Age    1.298384
18         Education_Master    9.148227
19            Education_PhD    8.566098
20  Education_Undergraduate   11.572186
21   Marital_Status_Married    2.940062
22    Marital_Status_Single    2.485269
23  Marital_Status_Together    2.617173


In [296]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
test = df.drop(['Response','Education_Undergraduate','Age','Z_CostContact','AcceptedCmp5','ID','Year_Birth','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5','Complain','Z_Revenue','Dt_Customer'],axis=1)
vif_data["feature"] = test.columns

# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(test.values, i)
                          for i in range(len(test.columns))]
  
print(vif_data)

                    feature       VIF
0                    Income  9.465001
1                   Kidhome  2.939774
2                  Teenhome  2.650447
3                   Recency  3.621852
4                  MntWines  4.927107
5                 MntFruits  2.793996
6           MntMeatProducts  4.428260
7           MntFishProducts  3.090606
8          MntSweetProducts  2.729060
9              MntGoldProds  2.586021
10        NumDealsPurchases  3.946138
11          NumWebPurchases  6.062276
12      NumCatalogPurchases  5.337865
13        NumStorePurchases  8.743050
14        NumWebVisitsMonth  7.640274
15             AcceptedCmp1  1.311858
16         Education_Master  1.467946
17            Education_PhD  1.552001
18   Marital_Status_Married  3.890776
19    Marital_Status_Single  2.616101
20  Marital_Status_Together  2.948095
21     Marital_Status_Widow  1.264986


In [250]:
df

         ID  Year_Birth   Income  Kidhome  Teenhome Dt_Customer  Recency  \
0      5524        1957  58138.0        0         0  2012-09-04       58   
1      2174        1954  46344.0        1         1  2014-03-08       38   
2      4141        1965  71613.0        0         0  2013-08-21       26   
3      6182        1984  26646.0        1         0  2014-02-10       26   
4      5324        1981  58293.0        1         0  2014-01-19       94   
...     ...         ...      ...      ...       ...         ...      ...   
2235  10870        1967  61223.0        0         1  2013-06-13       46   
2236   4001        1946  64014.0        2         1  2014-06-10       56   
2237   7270        1981  56981.0        0         0  2014-01-25       91   
2238   8235        1956  69245.0        0         1  2014-01-24        8   
2239   9405        1954  52869.0        1         1  2012-10-15       40   

      MntWines  MntFruits  MntMeatProducts  ...  Z_Revenue  Response  Age  \
0         

In [305]:
y_logr= df[['AcceptedCmp1']]
x_logr= df.drop(['AcceptedCmp1','Education_Undergraduate','Z_CostContact','ID','Year_Birth','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5','Complain','Z_Revenue','Dt_Customer','Response'],axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, z_train, z_test = train_test_split(x_logr, y_logr, test_size=0.20)

In [218]:
#(z_train.head(10))
z_test

      AcceptedCmp1
1130             0
1257             0
1586             0
1731             0
525              0
...            ...
689              0
2065             0
1506             0
538              0
784              0

[448 rows x 1 columns]

In [306]:
import statsmodels.api as sm


Xlog2 = sm.add_constant(x_train) 
logr_model = sm.Logit(z_train, Xlog2) 
logr_fit = logr_model.fit()
print(logr_fit.summary())


Optimization terminated successfully.
         Current function value: 0.161520
         Iterations 9
                           Logit Regression Results                           
Dep. Variable:           AcceptedCmp1   No. Observations:                 1789
Model:                          Logit   Df Residuals:                     1766
Method:                           MLE   Df Model:                           22
Date:                Sun, 20 Nov 2022   Pseudo R-squ.:                  0.3230
Time:                        20:38:42   Log-Likelihood:                -288.96
converged:                       True   LL-Null:                       -426.84
Covariance Type:            nonrobust   LLR p-value:                 9.735e-46
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -5.4492      0.910     -5.991      0.000      -7.232   

In [307]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression()

logreg.fit(x_train,z_train)


z_pred = logreg.predict(x_test)
cnf_matrix = confusion_matrix(z_test, z_pred)
cnf_matrix


array([[413,   6],
       [ 25,   4]], dtype=int64)

In [308]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr_bal=LogisticRegression(random_state=42,class_weight='balanced')
lr_bal_model=lr_bal.fit(x_train,z_train)
y_pred_cmp=lr_bal_model.predict(x_test)
print('Classification report for balanced classes \n',classification_report(z_test,y_pred_cmp))



Classification report for balanced classes 
               precision    recall  f1-score   support

           0       0.99      0.77      0.87       419
           1       0.21      0.90      0.34        29

    accuracy                           0.78       448
   macro avg       0.60      0.83      0.61       448
weighted avg       0.94      0.78      0.83       448



In [309]:
cnf_matrix = confusion_matrix(z_test, y_pred_cmp)
cnf_matrix


array([[323,  96],
       [  3,  26]], dtype=int64)

Choose significant variables

In [326]:
y_logr= df[['AcceptedCmp1']]
x_logr= df[['NumCatalogPurchases','Teenhome','MntWines']]
from sklearn.model_selection import train_test_split
x_train, x_test, z_train, z_test = train_test_split(x_logr, y_logr, test_size=0.20)

In [322]:
import statsmodels.api as sm


Xlog2 = sm.add_constant(x_train) 
logr_model = sm.Logit(z_train, Xlog2) 
logr_fit = logr_model.fit()
print(logr_fit.summary())


Optimization terminated successfully.
         Current function value: 0.178846
         Iterations 8
                           Logit Regression Results                           
Dep. Variable:           AcceptedCmp1   No. Observations:                 1789
Model:                          Logit   Df Residuals:                     1785
Method:                           MLE   Df Model:                            3
Date:                Sun, 20 Nov 2022   Pseudo R-squ.:                  0.2730
Time:                        20:51:30   Log-Likelihood:                -319.95
converged:                       True   LL-Null:                       -440.11
Covariance Type:            nonrobust   LLR p-value:                 8.133e-52
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  -4.3051      0.262    -16.423      0.000      -4.819      -3.791
Nu

array([[416,   1],
       [ 31,   0]], dtype=int64)

In [327]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr_bal=LogisticRegression(random_state=42,class_weight='balanced')
lr_bal_model=lr_bal.fit(x_train,z_train)
y_pred_cmp=lr_bal_model.predict(x_test)
print('Classification report for balanced classes \n',classification_report(z_test,y_pred_cmp))



Classification report for balanced classes 
               precision    recall  f1-score   support

           0       0.99      0.80      0.89       419
           1       0.23      0.86      0.36        29

    accuracy                           0.81       448
   macro avg       0.61      0.83      0.63       448
weighted avg       0.94      0.81      0.85       448



In [328]:
cnf_matrix = confusion_matrix(z_test, y_pred_cmp)
cnf_matrix

array([[336,  83],
       [  4,  25]], dtype=int64)

Run SVM

In [329]:
y_logr= df[['AcceptedCmp1']]
x_logr= df.drop(['AcceptedCmp1','Education_Undergraduate','Z_CostContact','ID','Year_Birth','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5','Complain','Z_Revenue','Dt_Customer','Response'],axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, z_train, z_test = train_test_split(x_logr, y_logr, test_size=0.20)

In [330]:
from sklearn import svm

svm_model = svm.SVC(kernel='linear',class_weight='balanced') # Linear Kernel

#Train the model using the training sets
svm_model.fit(x_train, z_train)

#Predict the response for test dataset
z_pred = svm_model.predict(x_test)
cnf_matrix = confusion_matrix(z_test, z_pred)
cnf_matrix

array([[289, 130],
       [  4,  25]], dtype=int64)

In [331]:
print('Classification report for balanced classes \n',classification_report(z_test,z_pred))

Classification report for balanced classes 
               precision    recall  f1-score   support

           0       0.99      0.69      0.81       419
           1       0.16      0.86      0.27        29

    accuracy                           0.70       448
   macro avg       0.57      0.78      0.54       448
weighted avg       0.93      0.70      0.78       448



In [216]:
from sklearn.feature_selection import RFE
svc_lin=SVC(kernel='linear')
svm_rfe_model=RFE(estimator=svc_lin)
svm_rfe_model_fit=svm_rfe_model.fit(x_train, z_train)
feat_index = pd.Series(data = svm_rfe_model_fit.ranking_, index = x_train.columns)
signi_feat_rfe = feat_index[feat_index==1].index
print('Significant features from RFE',signi_feat_rfe)

Significant features from RFE Index(['Kidhome', 'Teenhome', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'Age', 'Education_Master', 'Education_PhD',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Together'],
      dtype='object')


In [340]:
y_logr= df[['AcceptedCmp1']]
x_logr= df[['Teenhome','NumCatalogPurchases','MntWines']]

from sklearn.model_selection import train_test_split
x_train, x_test, z_train, z_test = train_test_split(x_logr, y_logr, test_size=0.20)

In [341]:
from sklearn import svm

svm_model = svm.SVC(kernel='linear',class_weight='balanced') # Linear Kernel

#Train the model using the training sets
svm_model.fit(x_train, z_train)

#Predict the response for test dataset
z_pred = svm_model.predict(x_test)
cnf_matrix = confusion_matrix(z_test, z_pred)
cnf_matrix

array([[334,  92],
       [  6,  16]], dtype=int64)

In [342]:
print('Classification report for balanced classes \n',classification_report(z_test,z_pred))

Classification report for balanced classes 
               precision    recall  f1-score   support

           0       0.98      0.78      0.87       426
           1       0.15      0.73      0.25        22

    accuracy                           0.78       448
   macro avg       0.57      0.76      0.56       448
weighted avg       0.94      0.78      0.84       448

